version: "3.8"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./app
    command: celery -A portfolio worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A portfolio beat -l info
    volumes:
      - ./app/:/usr/arc/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data_images/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres_db
volumes:
  postgres_data: